# Database Configuration
# Host: db.[project-ref].supabase.co
spring.datasource.url=jdbc:postgresql://db.vbgrlsngqobtxkpuxopj.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres

# สำคัญ: นี่คือรหัสผ่านที่คุณตั้งตอนสร้าง Project (ไม่ใช่ API Key ในรูปภาพ)
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.expiration=86400000

# Spring จะไปอ่านค่าจาก Environment ของ OS (Container)
jwt.secret=${APP_JWT_SECRET}
